version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Pacific/Auckland"
    open-pull-requests-limit: 2
